### ISSUE TITLE
Emoji not found!

### ISSUE THREAD

**Issue by RC047** [DevSnowflake/emoji-api#3]
I have checked this because of the problem when I will get a url request getting a status code of 403 (Forbidden)

**Comment by officialdittaz** [comment]
Same with me

**Comment by twlite** [comment]
I will take a look at this

**Comment by twlite** [comment]
Emojipedia has a bot protection enabled due to which we can't fetch data from it.

emoji-api v3 removes emojipedia completely, which means codebase depending upon v2 will have to migrate to v3 api as the api between these two versions are incompatible. v3 no longer depends upon external services so this issue should no longer occur. But the trade-off here is `emoji-api` may not be up-to-date.

Edit: Release can be found @ https://github.com/archaeopteryx1/emoji-api/releases/tag/v3.0.0

**Comment by RC047** [comment]
> Emojipedia has a bot protection enabled due to which we can't fetch data from it.
> 
> emoji-api v3 removes emojipedia completely, which means codebase depending upon v2 will have to migrate to v3 api as the api between these two versions are incompatible. v3 no longer depends upon external services so this issue should no longer occur. But the trade-off here is `emoji-api` may not be up-to-date.
> 
> Edit: Release can be found @ https://github.com/archaeopteryx1/emoji-api/releases/tag/v3.0.0

How about using source (https://unicode-table.com) ?

I have checked this is almost the same as the source (https://emojipedia.org)
which has various types of emoji. (this is just a suggestion)
